#! /bin/sh

# find all java source files in src directory
FILES=$(find src -iname "*.java")

rm -rf bin
mkdir -p bin

# compile each source file into bin directory, exiting on compilation failure
for file in $FILES
do
    echo "compiling $file"
    javac -cp "./src/" -d bin $file 2>/dev/null
    if [ $? -ne 0 ]
    then
        echo "compile failed"
        exit 1
    fi
done

echo "done"
